// Package launcher provides a named binary wrapper for Node.js CLI daemons.
//
// SDK SCOPE — what this package does:
//   - Spawn node with the consumer's .cjs bundle
//   - Manage a Windows Job Object (kill node when launcher exits)
//   - Forward OS signals from the launcher to node
//   - Write timestamped launcher logs to <configDir>/logs/
//   - Dispatch CLI commands to a running daemon via HTTP POST
//   - Detect a restart sentinel (<configDir>/config.restart) after node exits
//
// OUT OF SCOPE — the consumer is responsible for:
//   - Argument parsing (--config, -c, positional args, /cfg, etc.)
//   - Resolving which configDir to use from os.Args
//   - ALL business logic: update checks, auto-update, PID files, tray, etc.
//   - Any flag convention: the SDK does not interpret named flags
//
// Usage: call Run() from the consumer's main() with a fully resolved Config.
// The consumer's main.go.tmpl (generated by build.sh) handles arg parsing.
package launcher

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// waitDelay is the maximum time to wait for I/O pipes to close after the child
// process exits. Required when grandchildren (e.g. tray binary) inherit pipe
// handles — without this, cmd.Wait() blocks until all grandchildren exit.
// Value: 5s covers any normal tray/watcher shutdown; returns exec.ErrWaitDelay if exceeded.
const waitDelay = 5 * time.Second

// Config holds all project-specific settings for the launcher.
type Config struct {
	// ConfigDir is the path to the daemon's config directory
	// (where config.port and health_token live, e.g. ~/.config/myapp).
	ConfigDir string

	// NodeScript is the absolute path to the .cjs bundle to spawn in daemon mode.
	NodeScript string

	// CLIFlags lists the flags that trigger HTTP dispatch instead of daemon spawn.
	// Example: []string{"--quit", "--sync-now", "--pause", "--resume", "--restart"}
	CLIFlags []string

	// DefaultPort is used for error messages when config.port is absent. Defaults to 47823.
	DefaultPort int

	// AppName is the binary name used in user-facing error messages (e.g. "myapp").
	// Defaults to the executable basename when empty.
	AppName string

	// SilentFlags lists flags for which the launcher suppresses its own INFO/WARN
	// log output on stderr. Error logs are always shown. File logging is unaffected.
	// Use for short-lived pass-through commands (--help, --version, --pid) where
	// launcher lifecycle noise would obscure the actual command output.
	SilentFlags []string

	// Args overrides os.Args[1:] when set. Use this to pass pre-filtered args
	// (e.g. after stripping --config <dir> via ResolveConfigDir). When nil,
	// os.Args[1:] is used.
	Args []string

	// UpdateCmd is the command spawned when the daemon writes a config.update
	// sentinel before exiting to request an in-place binary update.
	// On Windows, the launcher exits immediately after spawning this command so
	// that the running .exe is no longer locked and npm can overwrite it.
	//
	// Only "npm install -g @wadeck/<pkg>[@<version>]" is accepted (exactly 4 args).
	// Any other command is rejected to prevent launcher.config.json injection attacks.
	// Leave nil or empty to disable update support (config.update sentinel is ignored).
	UpdateCmd []string `json:"updateCmd,omitempty"`
}

// validateUpdateCmd checks that UpdateCmd is a safe npm install command.
// Allowed: exactly ["npm", "install", "-g", "@wadeck/<pkg>[@<version>]"].
// Any other form is rejected to prevent launcher.config.json being used as a
// code-execution vector.
func validateUpdateCmd(cmd []string) error {
	if len(cmd) == 0 {
		// Not set — OK.
		return nil
	}
	if len(cmd) != 4 {
		return fmt.Errorf("updateCmd: expected exactly 4 args [npm install -g @wadeck/<pkg>], got %d", len(cmd))
	}
	if cmd[0] != "npm" || cmd[1] != "install" || cmd[2] != "-g" {
		return fmt.Errorf("updateCmd: only 'npm install -g @wadeck/<pkg>' is allowed, got %v", cmd)
	}
	pkg := cmd[3]
	if !strings.HasPrefix(pkg, "@wadeck/") {
		return fmt.Errorf("updateCmd: package must start with @wadeck/, got %q", pkg)
	}
	return nil
}

// Run is the launcher entrypoint — it never returns.
// It inspects os.Args and either dispatches a CLI command via HTTP
// or spawns the Node.js daemon process.
// --help, --version and any other flags not in CLIFlags are passed through to Node.
func appName(cfg Config) string {
	if cfg.AppName != "" {
		return cfg.AppName
	}
	if exe, err := os.Executable(); err == nil {
		return strings.TrimSuffix(filepath.Base(exe), ".exe")
	}
	return "app"
}

func Run(cfg Config) {
	if cfg.DefaultPort == 0 {
		cfg.DefaultPort = 47823
	}

	args := cfg.Args
	if args == nil {
		args = os.Args[1:]
	}

	// Suppress launcher INFO/WARN stderr output for short-lived pass-through commands
	// (e.g. --help, --version, --pid) so their output is not buried in lifecycle noise.
	for _, arg := range args {
		for _, silent := range cfg.SilentFlags {
			if arg == silent {
				setSilentMode(true)
				break
			}
		}
	}
	if isCLIDispatch(args, cfg.CLIFlags) {
		runCLIDispatch(cfg, args)
	} else {
		runDaemon(cfg, args)
	}
}

// isCLIDispatch returns true when any argument matches a known CLI flag.
func isCLIDispatch(args []string, cliFlags []string) bool {
	for _, arg := range args {
		for _, flag := range cliFlags {
			if arg == flag {
				return true
			}
		}
	}
	return false
}

// runCLIDispatch sends a command to the running daemon via HTTP and exits.
// Node.js is never launched.
func runCLIDispatch(cfg Config, args []string) {
	pf, err := readPortFile(cfg.ConfigDir)
	if err != nil {
		logError(cfg.ConfigDir, "dispatch", err.Error())
		fmt.Fprintln(os.Stderr, formatDaemonNotRunning(appName(cfg), cfg.ConfigDir))
		os.Exit(1)
	}

	token, err := readHealthToken(cfg.ConfigDir)
	if err != nil {
		logError(cfg.ConfigDir, "dispatch", err.Error())
		fmt.Fprintln(os.Stderr, formatDaemonNotRunning(appName(cfg), cfg.ConfigDir))
		os.Exit(1)
	}

	// Extract command name: first --flag that matches a known CLIFlag.
	// Positional args (no "--" prefix) and unknown flags are ignored.
	command := ""
	for _, arg := range args {
		if strings.HasPrefix(arg, "--") {
			for _, flag := range cfg.CLIFlags {
				if arg == flag {
					command = strings.TrimPrefix(arg, "--")
					break
				}
			}
			if command != "" {
				break
			}
		}
	}
	if command == "" {
		fmt.Fprintln(os.Stderr, "Error: no recognised command flag found in arguments")
		os.Exit(1)
	}

	url := fmt.Sprintf("http://127.0.0.1:%d/%s", pf.Port, command)
	logInfo(cfg.ConfigDir, "dispatch", fmt.Sprintf("POST %s (pid %d)", url, pf.Pid))

	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader([]byte("{}")))
	if err != nil {
		logError(cfg.ConfigDir, "dispatch", fmt.Sprintf("build request: %v", err))
		os.Exit(1)
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		logError(cfg.ConfigDir, "dispatch", fmt.Sprintf("HTTP error: %v", err))
		fmt.Fprintln(os.Stderr, formatDaemonNotResponding(appName(cfg), pf.Port, cfg.ConfigDir))
		os.Exit(1)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		logError(cfg.ConfigDir, "dispatch", fmt.Sprintf("HTTP %d: %s", resp.StatusCode, body))
		fmt.Fprintln(os.Stderr, formatHTTPError(appName(cfg), resp.StatusCode, command, cfg.ConfigDir))
		os.Exit(1)
	}

	logInfo(cfg.ConfigDir, "dispatch", fmt.Sprintf("command '%s' OK", command))
	fmt.Println(strings.TrimSpace(string(body)))
	os.Exit(0)
}

type sentinelAction int

const (
	sentinelNone    sentinelAction = iota
	sentinelRestart                // restart the daemon
	sentinelUpdate                 // spawn update command and exit
)

type sentinelResult struct {
	action sentinelAction
	reason string // human-readable for logging
}

// checkSentinels reads the config.update and config.restart sentinel files in configDir.
// Returns what action to take. Removes the relevant sentinel file if found.
// cfg is used to validate UpdateCmd when the update sentinel is present.
func checkSentinels(configDir string, cfg Config) sentinelResult {
	updateSentinelPath := filepath.Join(configDir, "config.update")
	restartSentinelPath := filepath.Join(configDir, "config.restart")

	// Check for update sentinel first.
	if _, err := os.Stat(updateSentinelPath); err == nil {
		if removeErr := os.Remove(updateSentinelPath); removeErr != nil {
			logWarn(configDir, "launcher", fmt.Sprintf("update sentinel found but could not remove (%v) — not triggering update", removeErr))
			return sentinelResult{action: sentinelNone, reason: "update sentinel remove failed"}
		}
		if len(cfg.UpdateCmd) == 0 {
			logWarn(configDir, "launcher", "update sentinel detected but UpdateCmd is not set — ignoring (set Config.UpdateCmd to enable auto-update)")
			// Fall through to restart check.
		} else if err := validateUpdateCmd(cfg.UpdateCmd); err != nil {
			logError(configDir, "launcher", fmt.Sprintf("updateCmd validation failed: %v — not spawning update", err))
			// Fall through to restart check.
		} else {
			logInfo(configDir, "launcher", fmt.Sprintf("update sentinel detected — spawning: %v", cfg.UpdateCmd))
			return sentinelResult{action: sentinelUpdate, reason: fmt.Sprintf("update sentinel: %v", cfg.UpdateCmd)}
		}
	}

	// Check for restart sentinel.
	if _, err := os.Stat(restartSentinelPath); err == nil {
		logInfo(configDir, "launcher", "restart sentinel detected — relaunching")
		if removeErr := os.Remove(restartSentinelPath); removeErr == nil {
			return sentinelResult{action: sentinelRestart, reason: "restart sentinel"}
		} else {
			logWarn(configDir, "launcher", fmt.Sprintf("restart sentinel found but could not remove (%v) — not relaunching", removeErr))
			return sentinelResult{action: sentinelNone, reason: "restart sentinel remove failed"}
		}
	} else {
		sentinelMsg := formatSentinelReadError(restartSentinelPath, err)
		if os.IsNotExist(err) {
			logInfo(configDir, "launcher", sentinelMsg)
		} else {
			logWarn(configDir, "launcher", sentinelMsg)
		}
	}

	return sentinelResult{action: sentinelNone, reason: "no sentinel found"}
}

// runDaemon spawns node.exe with the .cjs script and stays alive until it exits.
// On Windows a Job Object ensures the child is killed when this process dies.
func runDaemon(cfg Config, args []string) {
	if ppid := os.Getppid(); ppid == 1 {
		logInfo(cfg.ConfigDir, "launcher", "launched by launchd (login agent, ppid=1)")
	} else {
		logInfo(cfg.ConfigDir, "launcher", fmt.Sprintf("launched manually (ppid=%d)", ppid))
	}

	nodePath, err := exec.LookPath("node")
	if err != nil {
		logError(cfg.ConfigDir, "launcher", "node not found in PATH - install Node.js and ensure it is in PATH")
		os.Exit(1)
	}

	// Allow the npm shim to override the bundle path when launcher and bundle
	// are in different npm packages (exe-in-npm distribution pattern).
	if override := os.Getenv("LAUNCHER_BUNDLE_OVERRIDE"); override != "" {
		cfg.NodeScript = override
	}

	scriptArgs := append([]string{cfg.NodeScript}, args...)
	cmd := exec.Command(nodePath, scriptArgs...)
	cmd.WaitDelay = waitDelay
	setCmdFlags(cmd)

	// Always give node explicit stdio handles via STARTF_USESTDHANDLES so that
	// libuv initialises correctly in all execution contexts:
	//   - Interactive terminal: pass the launcher's real console handles through.
	//   - Headless (spawned by the updater helper with stdio:'ignore'): open the
	//     NUL device explicitly. cmd.Stdin/Stdout/Stderr = nil does NOT set
	//     STARTF_USESTDHANDLES — node would inherit the launcher's handles, which
	//     may be null/invalid DETACHED_PROCESS handles that crash libuv on startup.
	if hasConsole() {
		cmd.Stdin = os.Stdin
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
	} else {
		stdin, stdout, stderr := openNulStdio()
		cmd.Stdin = stdin
		cmd.Stdout = stdout
		cmd.Stderr = stderr
	}

	logInfo(cfg.ConfigDir, "launcher", fmt.Sprintf("configDir=%s", cfg.ConfigDir))
	logInfo(cfg.ConfigDir, "launcher", fmt.Sprintf("spawning %s %s", nodePath, strings.Join(scriptArgs, " ")))

	if err := cmd.Start(); err != nil {
		logError(cfg.ConfigDir, "launcher", formatNodeStartError(cfg.NodeScript, err))
		os.Exit(1)
	}

	launcherPID := os.Getpid()
	if pidErr := writeLauncherPIDFile(cfg.ConfigDir, launcherPID); pidErr != nil {
		logWarn(cfg.ConfigDir, "launcher", fmt.Sprintf("could not write launcher PID file: %v", pidErr))
	}
	logInfo(cfg.ConfigDir, "launcher", fmt.Sprintf("PIDs: launcher=%d node=%d", launcherPID, cmd.Process.Pid))

	if err := assignJobObject(cmd); err != nil {
		logWarn(cfg.ConfigDir, "launcher", fmt.Sprintf("Job Object setup failed (non-fatal): %v", err))
	}

	stopSignals := forwardSignals(cmd)

	// cmd.Wait() with WaitDelay=5s:
	// - os.Stdout/Stderr are *os.File so no I/O goroutines are created.
	// - cmd.Wait() returns as soon as node exits in the normal case.
	// - If grandchildren (tray binary) still hold handle copies, WaitDelay
	//   force-closes after 5s and returns exec.ErrWaitDelay — still treated as
	//   a clean exit since node itself has already exited.
	exitCode := 0
	if err := cmd.Wait(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
			logInfo(cfg.ConfigDir, "launcher", fmt.Sprintf("node exited with code %d", exitCode))
		} else if err == exec.ErrWaitDelay {
			logInfo(cfg.ConfigDir, "launcher", "node exited (WaitDelay triggered for grandchildren)")
		} else {
			logError(cfg.ConfigDir, "launcher", fmt.Sprintf("node wait error: %v", err))
			exitCode = 1
		}
	} else {
		logInfo(cfg.ConfigDir, "launcher", "node exited cleanly")
	}

	close(stopSignals)

	// Check sentinels written by Node before it exited.
	// Node cannot spawn a new launcher binary outside the Job Object — only the Go
	// launcher (which is not in the Job Object) can safely re-spawn or trigger an update.
	logInfo(cfg.ConfigDir, "launcher", fmt.Sprintf("post-exit check: exitCode=%d", exitCode))
	if exitCode == 0 {
		result := checkSentinels(cfg.ConfigDir, cfg)
		switch result.action {
		case sentinelUpdate:
			spawnUpdateAndExit(cfg.ConfigDir, cfg.UpdateCmd)
			// spawnUpdateAndExit calls os.Exit — unreachable.
		case sentinelRestart:
			runDaemon(cfg, args)
			return
		case sentinelNone:
			// No sentinel — fall through to os.Exit below.
		}
	}

	os.Exit(exitCode)
}

// DefaultConfigDir returns the XDG-standard config directory for the given app name.
// Resolution order:
//  1. $XDG_CONFIG_HOME/<appName> if $XDG_CONFIG_HOME is set
//  2. $HOME/.config/<appName> otherwise
//
// No dot prefix is added to appName — pass a bare app name (e.g. "flow", "wdrive").
// On Windows, APPDATA is intentionally ignored to keep behaviour consistent across platforms.
func DefaultConfigDir(appName string) string {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, appName)
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(".", ".config", appName)
	}
	return filepath.Join(home, ".config", appName)
}

// ResolveConfigDir resolves the config directory for appName from CLI args, environment,
// and filesystem, and performs a one-time legacy path migration when necessary.
//
// Resolution order (highest to lowest priority):
//  1. --config <dir> in args — consumed from the returned remainingArgs slice
//  2. $XDG_CONFIG_HOME/<appName> if $XDG_CONFIG_HOME is set
//  3. $HOME/.config/<appName> otherwise
//
// Migration: if the legacy path ~/.<appName> exists and the resolved new path does not,
// it is automatically renamed and a message is printed to stderr.
// Migration is skipped when --config is used (custom dirs need no migration).
func ResolveConfigDir(appName string, args []string) (configDir string, remainingArgs []string) {
	// Priority 1: --config <dir> from CLI args
	configDir, remainingArgs = extractConfigArg(args)
	if configDir != "" {
		// Expand ~/ to home dir (shell does not expand ~ for detached processes).
		if strings.HasPrefix(configDir, "~/") || strings.HasPrefix(configDir, "~\\") {
			if home, err := os.UserHomeDir(); err == nil {
				configDir = filepath.Join(home, configDir[2:])
			}
		}
		// Custom dir supplied: skip migration (user manages this dir explicitly).
		return configDir, remainingArgs
	}
	remainingArgs = args

	// Priority 2 & 3: XDG / HOME
	configDir = DefaultConfigDir(appName)

	// Migration: ~/.<appName> → new XDG path
	if home, err := os.UserHomeDir(); err == nil {
		legacyPath := filepath.Join(home, "."+appName)
		migrateConfigDir(legacyPath, configDir)
	}

	return configDir, remainingArgs
}

// extractConfigArg scans args for "--config <dir>" and returns the dir and the
// remaining args with the "--config <dir>" pair removed.
// Also accepts a bare positional path as the first argument (legacy format:
// "wdrive.exe /path/to/configDir") for backward compatibility with registry
// entries created before the --config flag was introduced.
// Returns an empty string and the original args when no config dir is found.
func extractConfigArg(args []string) (configDir string, remainingArgs []string) {
	remainingArgs = make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		if args[i] == "--config" && i+1 < len(args) {
			configDir = args[i+1]
			// Skip both "--config" and its value
			i++
		} else if configDir == "" && i == 0 && looksLikePath(args[i]) {
			// Legacy positional config dir: first arg is a bare directory path.
			// Consumed here so the launcher and Node agree on the config dir.
			configDir = args[i]
		} else {
			remainingArgs = append(remainingArgs, args[i])
		}
	}
	return configDir, remainingArgs
}

// looksLikePath returns true when s appears to be an absolute or home-relative
// directory path rather than a flag or subcommand name.
func looksLikePath(s string) bool {
	if len(s) == 0 {
		return false
	}
	// Unix absolute or home-relative
	if s[0] == '/' || s[0] == '~' {
		return true
	}
	// Windows absolute: C:\... or C:/...
	if len(s) >= 3 && s[1] == ':' && (s[2] == '\\' || s[2] == '/') {
		return true
	}
	return false
}

// migrateConfigDir renames oldPath to newPath when oldPath exists and newPath does not.
// A message is printed to stderr on success or failure.
func migrateConfigDir(oldPath, newPath string) {
	if _, err := os.Stat(oldPath); os.IsNotExist(err) {
		// Nothing to migrate.
		return
	}
	if _, err := os.Stat(newPath); err == nil {
		// New path already exists — do not overwrite.
		return
	}
	// Ensure parent directory exists.
	if err := os.MkdirAll(filepath.Dir(newPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "warning: config migration: could not create parent dir %s: %v\n", filepath.Dir(newPath), err)
		return
	}
	if err := os.Rename(oldPath, newPath); err != nil {
		fmt.Fprintf(os.Stderr, "warning: config migration: could not rename %s → %s: %v\n", oldPath, newPath, err)
		return
	}
	fmt.Fprintf(os.Stderr, "info: config dir migrated from %s to %s\n", oldPath, newPath)
}
